import React from 'react';

const COMPARISON_ROWS = [
  {
    capability: 'Full IELTS exam simulation',
    letsCrack: 'Yes, timed + official format',
    youtube: 'No, fragmented videos',
    coaching: 'Limited mock sessions',
  },
  {
    capability: 'Writing & speaking feedback',
    letsCrack: 'Instant AI scoring + corrections',
    youtube: 'No personalised correction',
    coaching: 'Manual, delayed feedback',
  },
  {
    capability: 'Personalized daily study plan',
    letsCrack: 'Auto-generated by weak skills',
    youtube: 'Self-planned only',
    coaching: 'Batch-level generic plan',
  },
  {
    capability: 'Progress analytics',
    letsCrack: 'Per-skill dashboard + trends',
    youtube: 'No tracking system',
    coaching: 'Basic periodic reports',
  },
  {
    capability: 'Learning flexibility',
    letsCrack: '24/7 access (any device)',
    youtube: 'Flexible but unstructured',
    coaching: 'Fixed class timings',
  },
];

export default function ComparisonSection() {
  return (
    <section id="comparison" className="section" style={{ background: '#fff' }}>
      <div className="container">
        
        {/* Header */}
        <div style={{ textAlign: 'center', maxWidth: '720px', margin: '0 auto 5rem' }} className="animate-fade-up">
          <p className="eyebrow" style={{ justifyContent: 'center' }}>How We're Different</p>
          <h2 style={{ fontSize: 'clamp(2.25rem, 5vw, 3rem)', marginBottom: '1.25rem' }}>
            LetsCrack vs YouTube vs<br />
            traditional coaching
          </h2>
          <p style={{ fontSize: '1.125rem', color: 'var(--color-ink-2)', lineHeight: 1.7 }}>
            A clean comparison of learning experience, feedback quality, and score-focused structure.
          </p>
        </div>

        {/* Table Wrapper */}
        <div 
          className="animate-fade-in"
          style={{
            background: 'white',
            borderRadius: '28px',
            border: '1px solid var(--color-border)',
            overflow: 'hidden',
            boxShadow: 'var(--shadow-lg)',
          }}
        >
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', minWidth: '800px' }}>
              <thead>
                <tr style={{ background: 'var(--color-surface-2)' }}>
                  <th style={HEADER_STYLE}>Capability</th>
                  <th style={{ ...HEADER_STYLE, color: 'var(--color-brand)', background: 'var(--color-brand-lt)' }}>
                    LetsCrack
                  </th>
                  <th style={HEADER_STYLE}>YouTube</th>
                  <th style={HEADER_STYLE}>Coaching Centers</th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON_ROWS.map((row, idx) => (
                  <tr key={idx} style={{ borderTop: '1px solid var(--color-border)' }}>
                    <td style={{ ...CELL_STYLE, fontWeight: 700, color: 'var(--color-ink)' }}>{row.capability}</td>
                    <td style={{ 
                      ...CELL_STYLE, 
                      fontWeight: 600, 
                      color: 'var(--color-brand)', 
                      background: 'var(--color-brand-lt)',
                      borderLeft: '1px solid rgba(26,86,219,0.1)',
                      borderRight: '1px solid rgba(26,86,219,0.1)'
                    }}>
                      {row.letsCrack}
                    </td>
                    <td style={{ ...CELL_STYLE, color: 'var(--color-ink-3)' }}>{row.youtube}</td>
                    <td style={{ ...CELL_STYLE, color: 'var(--color-ink-3)' }}>{row.coaching}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </section>
  );
}

const HEADER_STYLE: React.CSSProperties = {
  padding: '1.75rem 2rem',
  fontSize: '0.8125rem',
  fontWeight: 800,
  textTransform: 'uppercase',
  letterSpacing: '0.1em',
  color: 'var(--color-ink-3)',
};

const CELL_STYLE: React.CSSProperties = {
  padding: '1.75rem 2rem',
  fontSize: '0.9375rem',
  lineHeight: 1.5,
  color: 'var(--color-ink-2)',
  verticalAlign: 'middle',
};
