/* 
 * LETSCRACK IELTS — COMPARISON SECTION
 * Focus: Capability Matrix, Transparency, Premium Table Design
 * Style: Clean borders, highlighted brand column
 */

const COMPARISON_ROWS = [
  {
    capability: 'Full IELTS exam simulation',
    letsCrack: 'Yes, timed + official format',
    youtube: 'No, fragmented videos',
    coaching: 'Limited mock sessions',
  },
  {
    capability: 'Writing & speaking feedback',
    letsCrack: 'Instant AI scoring + corrections',
    youtube: 'No personalised correction',
    coaching: 'Manual, delayed feedback',
  },
  {
    capability: 'Personalized daily study plan',
    letsCrack: 'Auto-generated by weak skills',
    youtube: 'Self-planned only',
    coaching: 'Batch-level generic plan',
  },
  {
    capability: 'Progress analytics',
    letsCrack: 'Per-skill dashboard + trend lines',
    youtube: 'No tracking system',
    coaching: 'Basic periodic reports',
  },
  {
    capability: 'Learning flexibility',
    letsCrack: '24/7 access from any device',
    youtube: 'Flexible but unstructured',
    coaching: 'Fixed class timings',
  },
];

export default function ComparisonSection() {
  return (
    <section id="comparison" className="section" style={{ background: '#fff' }}>
      <div className="container">
        
        {/* Header */}
        <div style={{ textAlign: 'center', maxWidth: '720px', margin: '0 auto 4rem' }}>
          <p className="eyebrow" style={{ justifyContent: 'center' }}>How We're Different</p>
          <h2 style={{ 
            fontSize: 'clamp(2.25rem, 5vw, 3rem)', 
            fontWeight: 800, 
            color: 'var(--color-ink)', 
            marginBottom: '1.25rem',
            fontFamily: 'var(--font-display)',
            letterSpacing: '-0.02em'
          }}>
            LetsCrack vs YouTube vs<br />
            traditional coaching
          </h2>
          <p style={{ fontSize: '1.125rem', color: 'var(--color-ink-2)', lineHeight: 1.7 }}>
            A clean comparison of learning experience, feedback quality, and score-focused structure.
          </p>
        </div>

        {/* Table Container */}
        <div style={{
          background: '#fff',
          borderRadius: '24px',
          border: '1px solid var(--color-border)',
          overflow: 'hidden',
          boxShadow: '0 8px 24px rgba(0,0,0,0.02)',
        }}>
          <div style={{ overflowX: 'auto' }}>
            <table style={{
              width: '100%',
              borderCollapse: 'collapse',
              textAlign: 'left',
              minWidth: '800px',
            }}>
              <thead>
                <tr style={{ background: '#f8fafc' }}>
                  <th style={HEADER_STYLE}>Capability</th>
                  <th style={{ ...HEADER_STYLE, color: 'var(--color-brand)', background: 'var(--color-brand-lt)', borderLeft: '1px solid #dbeafe', borderRight: '1px solid #dbeafe' }}>
                    LetsCrack
                  </th>
                  <th style={HEADER_STYLE}>YouTube</th>
                  <th style={HEADER_STYLE}>Coaching Centers</th>
                </tr>
              </thead>
              <tbody>
                {COMPARISON_ROWS.map((row, idx) => (
                  <tr key={row.capability} style={{ borderTop: '1px solid var(--color-border)' }}>
                    <td style={{ ...CELL_STYLE, fontWeight: 700, color: 'var(--color-ink)' }}>{row.capability}</td>
                    <td style={{ 
                      ...CELL_STYLE, 
                      fontWeight: 600, 
                      color: 'var(--color-brand)', 
                      background: 'var(--color-brand-lt)',
                      borderLeft: '1px solid #dbeafe',
                      borderRight: '1px solid #dbeafe'
                    }}>
                      {row.letsCrack}
                    </td>
                    <td style={{ ...CELL_STYLE, color: 'var(--color-ink-3)' }}>{row.youtube}</td>
                    <td style={{ ...CELL_STYLE, color: 'var(--color-ink-3)' }}>{row.coaching}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </section>
  );
}

const HEADER_STYLE: React.CSSProperties = {
  padding: '1.5rem 2rem',
  fontSize: '0.8125rem',
  fontWeight: 800,
  textTransform: 'uppercase',
  letterSpacing: '0.05em',
  color: 'var(--color-ink-4)',
  fontFamily: 'var(--font-display)',
};

const CELL_STYLE: React.CSSProperties = {
  padding: '1.5rem 2rem',
  fontSize: '0.9375rem',
  lineHeight: 1.5,
  color: 'var(--color-ink-2)',
  verticalAlign: 'top',
};
